Traceback (most recent call last):
  File "/vscmnt/brussel_pixiu_data/_data_brussel/vo/000/bvo00012/vsc11137/source2suffering/main.py", line 465, in <module>
    with open(data_dir+'{}/{}/gridscale_aggregated_pop_frac_le_test_{}.pkl'.format(flags['version'],flags['extr']+'_le_test',flags['extr']), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/brussel/vo/000/bvo00012/vsc11137/source2suffering/data/pickles_v3/tropicalcyclonedarea_le_test/gridscale_aggregated_pop_frac_le_test_tropicalcyclonedarea.pkl'
